"""Generates the Hmelj hops-cone mark, in both forms it has to exist in.

Run from the repo root:

    python3 scripts/gen-icon.py public/icons/icon.svg \
        Android/app/src/hmelj/res/drawable/ic_launcher_foreground.xml
    npm run icons        # re-renders the PNGs from the new icon.svg

Outputs:

    public/icons/icon.svg                                  (PWA / favicon source)
    Android/app/src/hmelj/res/drawable/ic_launcher_foreground.xml

Both come out of this one file on purpose. The Android vector used to be a
hand-transcribed copy of the SVG's path data, which is fine for a dozen
hand-placed paths and hopeless for forty generated ones — they would drift the
first time anybody nudged a number.

Two things make the drawing read as a hop cone rather than a brick wall:
  - rows are emitted BOTTOM-UP, so each higher row overlaps the one below and
    only the rounded belly of each bract stays visible (shingles hang down);
  - each row sags towards the middle, the way a band wrapping an ovoid does,
    so the tiling follows a 3D form instead of lying flat.
The bracts are tiled generously past the outline and clipped to a single
silhouette path, so the edge stays clean however the tiling happens to land.
"""
import io, sys

BG      = '#0b57d0'   # same brand blue the old pigeon icon used
BRACT_A = '#f0fadb'
BRACT_B = '#c2e079'
EDGE    = '#6ea233'
STEM    = '#8fd14f'
PAPER   = '#ffffff'   # the envelope, carried over from the pigeon icon it replaced
INK     = '#083a8c'

# Shorter and 18px higher than the cone drew alone: the envelope needs room at
# the base, and once it was added the whole thing sat low in the frame. The
# shift is baked into these coordinates rather than applied as a transform, so
# the SVG and the Android vector stay literally identical path data.
CONE = ("M256,118 C200,118 154,162 152,222 C150,282 180,338 214,374 "
        "C232,392 248,400 256,406 C264,400 280,392 298,374 "
        "C332,338 362,282 360,222 C358,162 312,118 256,118 Z")
BINE  = "M256,128 C250,102 248,88 254,68"
LEAF_L = "M250,82 C222,64 192,68 174,90 C200,110 230,108 250,82 Z"
LEAF_R = "M258,82 C286,64 316,68 334,90 C308,110 278,108 258,82 Z"

# The envelope sits BEHIND the cone, drawn before it, so the cone keeps its whole
# pointed silhouette and its tip rests inside the envelope's mouth. Drawing it in
# front instead was tried first and read as a hot-air balloon in a basket: it cut
# the taper off flat, and the cone above a separate box below is exactly the
# balloon shape. Behind, the flap's two diagonals emerge either side of the tip
# and the pair reads as one object.
EV_X, EV_Y, EV_W, EV_H, EV_R = 171, 352, 170, 92, 12
ENVELOPE = (f"M{EV_X+EV_R},{EV_Y} L{EV_X+EV_W-EV_R},{EV_Y} A{EV_R},{EV_R} 0 0 1 {EV_X+EV_W},{EV_Y+EV_R} "
            f"L{EV_X+EV_W},{EV_Y+EV_H-EV_R} A{EV_R},{EV_R} 0 0 1 {EV_X+EV_W-EV_R},{EV_Y+EV_H} "
            f"L{EV_X+EV_R},{EV_Y+EV_H} A{EV_R},{EV_R} 0 0 1 {EV_X},{EV_Y+EV_H-EV_R} "
            f"L{EV_X},{EV_Y+EV_R} A{EV_R},{EV_R} 0 0 1 {EV_X+EV_R},{EV_Y} Z")
FLAP = (f"M{EV_X+7},{EV_Y+11} L{EV_X+EV_W/2:.0f},{EV_Y+45} L{EV_X+EV_W-7},{EV_Y+11}")

# Bract half-width / belly depth / row pitch / mid-row sag. Sized so roughly
# three columns show across the cone: fewer, larger scales survive a 48px
# favicon, where the first draft's finer tiling turned to mush.
BW, BD, STEP, SAG = 50, 72, 40, 28

def bract(x, y):
    return (f"M{x-BW:.0f},{y:.0f} C{x-BW:.0f},{y+BD*0.74:.0f} {x-BW*0.52:.0f},{y+BD:.0f} {x:.0f},{y+BD:.0f} "
            f"C{x+BW*0.52:.0f},{y+BD:.0f} {x+BW:.0f},{y+BD*0.74:.0f} {x+BW:.0f},{y:.0f} "
            f"C{x+BW:.0f},{y-BD*0.30:.0f} {x+BW*0.52:.0f},{y-BD*0.42:.0f} {x:.0f},{y-BD*0.42:.0f} "
            f"C{x-BW*0.52:.0f},{y-BD*0.42:.0f} {x-BW:.0f},{y-BD*0.30:.0f} {x-BW:.0f},{y:.0f} Z")

def bracts():
    """(pathData, fill) bottom row first."""
    rows, y, i = [], 102, 0
    while y < 500:
        offset = 0 if i % 2 == 0 else BW
        xs = [256 - 3 * BW + offset + k * 2 * BW for k in range(4)]
        rows.append((y, xs, BRACT_A if i % 2 == 0 else BRACT_B))
        y += STEP; i += 1
    out = []
    for (y, xs, fill) in reversed(rows):
        for x in xs:
            dx = (x - 256) / 150.0
            out.append((bract(x, y + SAG * max(0.0, 1.0 - dx * dx)), fill))
    return out

def svg():
    o = io.StringIO(); w = o.write
    w('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">\n')
    w('  <!-- Generated by scripts/gen-icon.py — edit there, not here. -->\n')
    w(f'  <rect width="512" height="512" rx="112" fill="{BG}"/>\n')
    w('  <!-- the bine it hangs from, with a leaf either side -->\n')
    w(f'  <path d="{BINE}" fill="none" stroke="{STEM}" stroke-width="12" stroke-linecap="round"/>\n')
    w(f'  <path d="{LEAF_L}" fill="{STEM}"/>\n')
    w(f'  <path d="{LEAF_R}" fill="{STEM}"/>\n')
    w('  <!-- envelope, behind the cone -->\n')
    w(f'  <g transform="rotate(-4 256 402)">\n')
    w(f'    <path d="{ENVELOPE}" fill="{PAPER}" stroke="{INK}" stroke-width="8"/>\n')
    w(f'    <path d="{FLAP}" fill="none" stroke="{INK}" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>\n')
    w('  </g>\n')
    w('  <!-- one silhouette, bracts shingled inside it -->\n')
    w(f'  <clipPath id="cone"><path d="{CONE}"/></clipPath>\n')
    w(f'  <path d="{CONE}" fill="{BRACT_A}"/>\n')
    w('  <g clip-path="url(#cone)">\n')
    for d, fill in bracts():
        w(f'    <path d="{d}" fill="{fill}" stroke="{EDGE}" stroke-width="5"/>\n')
    w('  </g>\n')
    w(f'  <path d="{CONE}" fill="none" stroke="{EDGE}" stroke-width="10"/>\n')
    w('</svg>\n')
    return o.getvalue()

def mark():
    """The same artwork with no tile behind it.

    icon.svg carries the rounded blue square because that is what an app icon
    needs — a launcher, a PWA install and an apple-touch-icon all composite it
    onto something and expect it to fill the frame. Anywhere it is used as a
    LOGO rather than an icon (the login card, the docs sidebar, the README) that
    tile is wrong: it plants a blue box in the middle of the page. Same paths,
    no rect.

    Readable on either background by construction: the envelope is white with a
    navy outline, the cone pale green with an olive one, so neither disappears
    on white or on dark.
    """
    body = svg()
    rect = f'  <rect width="512" height="512" rx="112" fill="{BG}"/>\n'
    assert rect in body, 'background rect not found — svg() changed shape'
    return body.replace(rect, '', 1).replace(
        'Generated by scripts/gen-icon.py — edit there, not here.',
        'Generated by scripts/gen-icon.py — edit there, not here. Transparent logo variant.')

def android():
    o = io.StringIO(); w = o.write
    w('<?xml version="1.0" encoding="utf-8"?>\n')
    w('<!-- Generated by scripts/gen-icon.py, from the same geometry as\n')
    w('     public/icons/icon.svg (the PWA icon) — same 512x512 coordinate space,\n')
    w('     same path data. Regenerate both together; do not hand-edit this file.\n\n')
    w('     No background rect here: the adaptive icon draws that from\n')
    w('     ic_launcher_background.xml as a separate layer.\n\n')
    w('     The outer <group> scales the drawing to 0.8 about the canvas centre.\n')
    w('     Adaptive icons are masked to a circle/squircle/rounded-square of the\n')
    w('     launcher\'s choosing, with only the centred ~66% guaranteed visible,\n')
    w('     and the cone plus its leaves span y:86-456 — about 72% of the canvas,\n')
    w('     enough to get the leaf tips or the cone point clipped. At 0.8 the\n')
    w('     bounding box lands near x:171-341, y:120-416 (~58%), comfortably\n')
    w('     inside the safe zone, without hand-recomputing every path.\n\n')
    w('     <clip-path> needs API 21+; this module is minSdk 26 and adaptive\n')
    w('     icons are 26+ anyway. -->\n')
    w('<vector xmlns:android="http://schemas.android.com/apk/res/android"\n')
    w('    android:width="108dp"\n')
    w('    android:height="108dp"\n')
    w('    android:viewportWidth="512"\n')
    w('    android:viewportHeight="512">\n\n')
    w('    <group\n        android:pivotX="256"\n        android:pivotY="256"\n')
    w('        android:scaleX="0.8"\n        android:scaleY="0.8">\n\n')
    w('        <!-- the bine it hangs from, with a leaf either side -->\n')
    w(f'        <path android:fillColor="#00000000" android:strokeColor="{STEM}"\n')
    w(f'            android:strokeWidth="12" android:strokeLineCap="round"\n')
    w(f'            android:pathData="{BINE}" />\n')
    w(f'        <path android:fillColor="{STEM}" android:pathData="{LEAF_L}" />\n')
    w(f'        <path android:fillColor="{STEM}" android:pathData="{LEAF_R}" />\n\n')
    w('        <group android:pivotX="256" android:pivotY="402" android:rotation="-4">\n')
    w(f'            <path android:fillColor="{PAPER}" android:strokeColor="{INK}"\n')
    w(f'                android:strokeWidth="8" android:pathData="{ENVELOPE}" />\n')
    w(f'            <path android:fillColor="#00000000" android:strokeColor="{INK}"\n')
    w(f'                android:strokeWidth="8" android:strokeLineCap="round" android:strokeLineJoin="round"\n')
    w(f'                android:pathData="{FLAP}" />\n')
    w('        </group>\n')
    w('        <!-- cone body, then the bracts shingled inside its silhouette -->\n')
    w(f'        <path android:fillColor="{BRACT_A}" android:pathData="{CONE}" />\n')
    w('        <group>\n')
    w(f'            <clip-path android:pathData="{CONE}" />\n')
    for d, fill in bracts():
        w(f'            <path android:fillColor="{fill}" android:strokeColor="{EDGE}"\n')
        w(f'                android:strokeWidth="5" android:pathData="{d}" />\n')
    w('        </group>\n\n')
    w('        <!-- outline over the bract edges -->\n')
    w(f'        <path android:fillColor="#00000000" android:strokeColor="{EDGE}"\n')
    w(f'            android:strokeWidth="10" android:pathData="{CONE}" />\n')
    w('    </group>\n')
    w('</vector>\n')
    return o.getvalue()

io.open(sys.argv[1], 'w', encoding='utf-8').write(svg())
io.open(sys.argv[2], 'w', encoding='utf-8').write(android())
written = [sys.argv[1], sys.argv[2]]
# Optional third output: the transparent logo variant. Optional so the two-argument
# invocation documented in the README keeps working unchanged.
if len(sys.argv) > 3:
    io.open(sys.argv[3], 'w', encoding='utf-8').write(mark())
    written.append(sys.argv[3])
print('wrote', ', '.join(written))
